image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-auth-microservice:
  stage: build
  script:
    gradle auth-microservice:assemble auth-microservice:testClasses

checkStyle-auth-microservice:
  stage: staticAnalysis
  script:
    gradle auth-microservice:checkstyleMain auth-microservice:checkStyleTest
  allow_failure: true

PMD-auth-microservice:
  stage: staticAnalysis
  script:
    gradle auth-microservice:pmdMain
  allow_failure: true

test-auth-microservice:
  stage: test
  script:
    - gradle auth-microservice:test auth-microservice:jacocoTestReport
    - cat auth-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
