image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-activities-microservice:
  stage: build
  script:
    gradle activities-microservice:assemble activities-microservice:testClasses

checkStyle-activities-microservice:
  stage: staticAnalysis
  script:
    gradle activities-microservice:checkstyleMain activities-microservice:checkStyleTest
  allow_failure: true

PMD-activities-microservice:
  stage: staticAnalysis
  script:
    gradle activities-microservice:pmdMain
  allow_failure: true

test-activities-microservice:
  stage: test
  script:
    - gradle activities-microservice:test activities-microservice:jacocoTestReport
    - cat activities-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
